/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingmain;

/**
 *
 * @author gerahn10
 */
public class Ranking extends javax.swing.JFrame {

    public Player usuarios[];
    public int jugadorActivo;
    public Player[] ordenados;
    public Ranking() {
        initComponents();
    }
    public Ranking(Player [] user,int jugador) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuarios = user;
        this.ordenados=user;
        this.jugadorActivo = jugador;
        
        Ordenar();
        
         jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1.", ordenados[0]==null? "":""+ordenados[0].getNomC(), ordenados[0]==null? "":""+ordenados[0].getPuntos()},
                {"2.", ordenados[1]==null? "":""+ordenados[1].getNomC(), ordenados[1]==null? "":""+ordenados[1].getPuntos()},
                {"3.", ordenados[2]==null? "":""+ordenados[2].getNomC(), ordenados[2]==null? "":""+ordenados[2].getPuntos()},
                {"4.", ordenados[3]==null? "":""+ordenados[3].getNomC(), ordenados[3]==null? "":""+ordenados[3].getPuntos()},
                {"5.", ordenados[4]==null? "":""+ordenados[4].getNomC(), ordenados[4]==null? "":""+ordenados[4].getPuntos()},
                {"6.", ordenados[5]==null? "":""+ordenados[5].getNomC(), ordenados[5]==null? "":""+ordenados[5].getPuntos()},
                {"7.", ordenados[6]==null? "":""+ordenados[6].getNomC(), ordenados[6]==null? "":""+ordenados[6].getPuntos()},
                {"8.", ordenados[7]==null? "":""+ordenados[7].getNomC(), ordenados[7]==null? "":""+ordenados[7].getPuntos()},
                {"9.", ordenados[8]==null? "":""+ordenados[8].getNomC(), ordenados[8]==null? "":""+ordenados[8].getPuntos()},
                {"10.", ordenados[9]==null? "":""+ordenados[9].getNomC(), ordenados[9]==null? "":""+ordenados[9].getPuntos()},
                {null, null, null}
            },
            new String [] {
                "No.", "Nombre", "Puntos"
            }
        ));
    }
    
    public void Ordenar(){
        
        Player aux;
        
       for(int i =0;i<usuarios.length;i++){
       
           for(int j = i+1;j<usuarios.length;j++){
           if(ordenados[i] != null && ordenados[j] !=null){
               if(ordenados[i].getPuntos() < ordenados[j].getPuntos()){
               
               aux=ordenados[i];
               ordenados[i]=ordenados[j];
               
                   ordenados[j]=aux;
                   
               }
           }
           
           }
       
       } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        jLabel1.setText("Ranking");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1.", null, null},
                {"2.", null, null},
                {"3.", null, null},
                {"4.", null, null},
                {"5.", null, null},
                {"6.", null, null},
                {"7.", null, null},
                {"8.", null, null},
                {"9.", null, null},
                {"10.", null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Nombre", "Puntos"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MenuJuego volver = new MenuJuego(usuarios,jugadorActivo);
       volver.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
